site_name: MAKEEN LABS
site_description: MAKEEN CBY Training Labs
site_author: MAKEEN
# site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
repo_name: makeen/fintech-ye
repo_url: https://github.com/fintech-ye
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2023-2024 MAKEEN'

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: 'images/makeen_logo_white.png'

extra_css:
  - css/styles.css
  - css/dark-mode.css

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/fintech-ye/getting-started

# Extensions
markdown_extensions:
  - meta
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dockersamples
      repo: 101-tutorial
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list

# Page tree
nav:
  - Getting Started: tutorial/index.md
  - Our Application: tutorial/our-application/index.md
  - Updating our App: tutorial/updating-our-app/index.md
  - Sharing our App: tutorial/sharing-our-app/index.md
  - Persisting our DB: tutorial/persisting-our-data/index.md
  # - Using Bind Mounts: tutorial/using-bind-mounts/index.md
  - Multi-Container Apps: tutorial/multi-container-apps/index.md
  - Using Docker Compose: tutorial/using-docker-compose/index.md
  - Image Building Best Practices: tutorial/image-building-best-practices/index.md
  - What Next?: tutorial/what-next/index.md
